### ISSUE TITLE
high risk of dead loop in function "void uart_bt_send(uint8_t *buf, uint16_t len)"

### ISSUE THREAD

**Issue by xihua13104** [sj15712795029/bluetooth_stack#9]
void uart_bt_send(uint8_t *buf, uint16_t len)
{
    uint8_t index;
    for (index = 0; index < len ; index++) {
        /* Wait until the last send is complete, then send the data */
        while (USART_GetFlagStatus(USART2, USART_FLAG_TC) == RESET);
        USART_SendData(USART2, buf[index]);
    }
    while (USART_GetFlagStatus(USART2, USART_FLAG_TC) == RESET);
}

**if len > 255, there will be a dead loop because index is uint8.**

**Comment by sj15712795029** [comment]
Thanks!This problem has been fixed.
